spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

camunda.bpm.admin-user:
  id: aa
  password: aa

spring.h2.console:
  enabled: true
  path: /h2-console